### ISSUE TITLE
Invalid CSS

### ISSUE THREAD

**Issue by nitinsurana** [nitinsurana/repeatit#17]
Root Cause : 
85f4bb28a2a3478ab0e345abb3ace6d1150fca2c

Please don't commit commented CSS. Also, css commenting is `/* */` not `//`

**Comment by nitinsurana** [comment]
We have to show more recipes in small space, so let's not give un-necessary padding.

```
#results li {
    padding: 10px;   //revert to 5px 
}
```

**Comment by himadrighosh13** [comment]
Fixed with 369af811bb0fd389bd307eb68179632a35bb55fc
