### ISSUE TITLE
Search Option on the Main Screen

### ISSUE THREAD

**Issue by nitinsurana** [nitinsurana/repeatit#19]
Searching Login in the main window: 
1. Login Recipe comes under Edulastic.
2. But Search is not persistent when we change the tab/project. 
![search not persistent](https://cloud.githubusercontent.com/assets/7137160/13297501/ba1277dc-db58-11e5-882b-c8df61fd30d7.PNG)

**Comment by himadrighosh13** [comment]
Fixed e632d678726d08d2f3bf594124ec0225404b4dad
