### ISSUE TITLE
Searching in one project automatically fills the text for others but doesn't search

### ISSUE THREAD

**Issue by nitinsurana** [nitinsurana/repeatit#9]
Hi,

Please search `something` under any project's tab in extension popup and notice the search working as expected. But now click on any other project's tab, the search query remains in the search-input-box in this new tab but I never searched that in this project.

**Comment by nitinsurana** [comment]
Root Cause : 05199af7e7f198fe6d5f477140ed68c03f2e85d1

**Comment by himadrighosh13** [comment]
Fixed e632d678726d08d2f3bf594124ec0225404b4dad
